### ISSUE TITLE
[Todo] 8th November 2022 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#10]
- [x] Read type systems for TAG based architectecture
- [x] Phase questions for that
- [ ] Write about 3 to 4 more TAG based arhcitecture surveys
- [ ] Add figures to TAG based architecture section

Interesting Questios:
- TAG vs IntelSGX vs Rust (Protections provided)
- Efficiency mode and security mode or both
- Mixing them with a Multi-kernel paradimn

**Comment by Akilan1999** [comment]
2 tasks carried over to the next day.
The Aim to have more stable sleep schedule (8 - 9hr sleep)
