### ISSUE TITLE
[Todo] 9th November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#11]
- [x] Breakfast 
- [x] Speak with parents 
- [x] Found cool Turkish music 
- [ ] Writing time 
    - [x] Add figures to TAG based architecture section
    - [ ] Write 4 papers
- [x] Reading time

**Comment by Akilan1999** [comment]
Writing not started as had review with Rob for new changes discussions.
