### ISSUE TITLE
[Todo] 10th November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#12]
- [x] Meeting discussion points draft 
- [ ] Make expense planner and work hours to cover all expenses
- [x] PhD meeting at 11am 
- [ ] ID check student services 
- [ ] Continue writing on 4 papers for TAG based architecture 
- [x] Work on Solid understanding of research questions 
- [x] Peernet Stefan Proposal review and work on Peernet Test Framework

**Comment by Akilan1999** [comment]
Rest of the tasks carried over next day
