### ISSUE TITLE
[Todo] 11th November

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#13]
- [ ] PhD research work 
- [ ] Peernet Test Framework and call with Stefan 
- [x] Check bank balance
- [x] Student Rail card 
- [x] Plans for tomorrow confirmed 
- [x] Tech Open source session
