### ISSUE TITLE
[Todo] 13th November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#14]
- [x] Logging Peernet and Karaz hours yesterday 
- [x] Paying Rent (Amount not received yet, Task complete)
- [x] Brunch 
- [x] Clean up kitchen 
- [x] Base bathroom cleanup 
- [ ] Decenode (2 hours)
- [ ] PhD work 
- [x] Meetup with Jonas 
- [x] Peernet README and upload page

**Comment by Akilan1999** [comment]
Decenode replaced with Karaz work with Gaurav.
PhD work not able to start.
