### ISSUE TITLE
[Todo] 14th November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#15]
- [x] Breakfast
- [x] Log Karaz hours
- [x] Survey 4 papers TAG Based architecture 
- [x] Lunch 
- [ ] Analyse Uni-kernels section 
- [x] Peernet Meeting
- [x] Pay rent 
- [x] Dinner

**Comment by Akilan1999** [comment]
Analysing uni-kernel steps 
- [ ] Finish OSv measurements to the table 
- [ ] Add Azelea Unikernel to the Latex table
- [x] Read on multi-kernel 

Carried over tomorrow.
