### ISSUE TITLE
[todo] 15th November

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#16]
- [ ] Analysis Uni-kernels
    - [x] Finish OSv measurements to the table 
    - [x] Add Azelea Unikernel to the Latex table
    - [x] Analysis sub headings for Uni-kernel 
    - [ ]  Start analysing 
- [x] Speaking with Humaid

**Comment by Akilan1999** [comment]
Heavy procrastination barley started. really ineffective day
