### ISSUE TITLE
[Todo] 16th November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#17]
- [x] Brushing and Shower 
- [x] Breakfast (Late)
- [ ] Uni-kernels analysis 
    - [ ] Write in-depth tasks in the morning 
        - [x] Best suitable tool for various platforms supported 
        - [ ] Best suitable for various architectures 
        - [ ] Best implementation for performance 
        - [ ] How do each of them handle parallel applications 
        - [ ] Best of tools with the most concrete evaluation 
    - [ ] Decide tasks before lunch 
- [ ] Lunch (And attend Hans-Wolfgang lecture)
- [ ] 1 hour NAP
- [ ] Execute tasks after Lunch 
- [ ] Decision on meeting discussion agenda
