### ISSUE TITLE
[Todo] 21st November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#18]
- [ ] Uni-kernel analysis plan 
    - [ ] Multi-core support 
    - [ ] Tools with Concrete Evaluation 
    - [ ] Tools for suitable for HPC applications 
- [ ] Uni-kernel analysis 
- [ ] Survey on Halvm and Ocaml implementation

**Comment by Akilan1999** [comment]
Still require a bit of progress most not complete
