### ISSUE TITLE
[Todo] 22nd November 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#19]
- [ ] Shower 
- [ ] Finish RKOS 
- [ ] Finish other Rest as well for multi-core as well. 
- [ ] Quick analysis for both and jump to Halvm and Mirage Survey. 
- [ ] Update tables and all reference

- [ ] Start on Multi-kernel intro and list 
- [ ] Same format
