### ISSUE TITLE
[todo] 3rd December

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#21]
- [ ] Get full formal questions 
    - [ ] Acceleration using TAG based architecture 
    - [ ] Safety features provided by Unikernels 
    - [ ] Safety features provided by TAG based architecture 
    - [ ] What both combined can provide 
    - [ ] Acceleration benefits using Multi-kernels
- [ ] Start a plan for analysis for TAG based architecture 
- [ ] Write Multi-kernel survey 

Avoid:
- [ ] Checking Hotmail, Migadu, Youtube, WhatsApp 
- [ ] No email responses until Monday 
- [x] Avoid speaking to any undergrads
