### ISSUE TITLE
[todo] 26th December 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#23]
## Before Start 
- [x] Breakfast 
## PhD 
- [x] Finish Task planner description for the experiment plan.
- [x] Introduction for the PhD report
## After PhD 
- [x] Lunch 
## Open source project work 
- [x] Xplane 11 Cluster Configuration 
- [x] 16:00 -> Call with Ahmed 
## Paid work 
- [ ] Karaz Documentation work (2 hours)
- [x] Dinner
