### ISSUE TITLE
[30th October] Todo 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#3]
- [ ] Year 1 report (Make current progress reviewable).
- [x] Karaz continue work.
- [ ] House maintenance plan and cooking plan.
- [ ] 6:30 [Oraim workout]

**Comment by Akilan1999** [comment]
Plans changed to meet a friend in Glasgow. 
"House maintenance plan and cooking plan." (Carried over to next Sunday) 
Year 1 report -> Catch up tomorrow.
