### ISSUE TITLE
[31st October] Todo 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#4]
- [ ] Complete existing surveys in depth. 
- [x] Introduction parts for Uni-kernels
- [ ] Add figures and more in-depth research question 
- [ ] Sendable for review 
- [x] Work on DSG webpages

**Comment by Akilan1999** [comment]
Peernet work took most of the time during the day and heavy distractions. The 3 tasks will carry over the next day.
