### ISSUE TITLE
[1st November] Todo 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#5]
- [x] Hair Cut 
- [ ] Complete existing surveys in depth. 
- [x] Add figures and more in-depth research question 
- [ ] Sendable for review 
- [x] Peernet Team meeting 
- [x] Peernet Download custom webpage

**Comment by Akilan1999** [comment]
Most tasks complete. 
Carry on to 2nd 
- Add references 
- describe more on HermitCore 
- Send for review
