### ISSUE TITLE
[3rd November] Todo 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#7]
- [x] Supervisor meeting discussion points
- [x] Supervisor meeting 
- [ ] Peernet Afternoon Hackathon 
- [x] Review feedback of Supervisor meeting 
- [ ] Start TAG based architecture literature review

**Comment by Akilan1999** [comment]
Note: 
Supervisor meeting canceled due to timezone switch.
Peernet afternoon and TAG based research did not go per plan (Lack of sleep and Iron Bru being the cause).
