### ISSUE TITLE
[7th November] Todo:

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/Akilan1999#9]
- [x] Karaz Weekly metrics
- [x] Karaz invoice send
- [x] Peernet invoice send 
- [x] Peernet log yesterdays hours
- [ ] Continue of TAG based architecture Survey 
- [x] Peernet Weekly meeting
- [x] Dinner with Sid

**Comment by Akilan1999** [comment]
TAG based not started due to lack of time.
